apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: request-success-rate
  namespace: istio-system
spec:
  provider:
    type: prometheus
    address: http://prometheus.istio-system:9090
  query: |
    100 - sum(
              rate(
                  istio_requests_total{
                    reporter="destination",
                    destination_workload_namespace=~"$namespace",
                    destination_workload=~"$workload",
                    response_code!~"5.*"
                  }[$interval]
              )
          )
          /
          sum(
              rate(
                  istio_requests_total{
                    reporter="destination",
                    destination_workload_namespace=~"$namespace",
                    destination_workload=~"$workload"
                  }[$interval]
              )
          )
---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: request-duration
  namespace: istio-system
spec:
  provider:
    type: prometheus
    address: http://prometheus.istio-system:9090
  query: |
    histogram_quantile(0.99,
      sum(
        irate(
          istio_request_duration_milliseconds_bucket{
            reporter="destination",
            destination_workload=~"$workload",
            destination_workload_namespace=~"$namespace"
          }[$interval]
        )
      ) by (le)
    )