apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: public-gateway
  namespace: sock-shop
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
#        - frontend.transparent-sock-shop.de
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: grafana
#  namespace: istio-system
#spec:
#  hosts:
#    - "*"
#  gateways:
#    - public-gateway.istio-system.svc.cluster.local
#
#  http:
#    - route:
#        - destination:
#            host: flagger-grafana
