apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sock-shop/hawk-kustomization.yaml
  - sock-shop/istio-kustomization.yaml
  - sock-shop/sock-shop-kustomization.yaml
  - sock-shop/sock-shop-source.yaml