apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hawk-ns
resources:
  - 01.ns.yml
  - 02-collector-db-dep.yaml
  - 03-collector-db-svc.yml
  - 06-collector-dep.yaml
  - 07-collector-svc.yml
  - 09-actixgo.filter.config.yaml
  - 10-actixgo.filter.inbound.yaml
  - 11.basic-collector.deploy.yaml
  - 12.basic-collector.svc.yaml
  - 13.rabbitmq.deploy.yaml
  - 14.rabbitmq.svc.yaml
  - 15.collector-cli.deploy.yaml
  - 16.grafana.deploy.yaml
  - 17.grafana.svc.yaml