apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
resources:
  - 01-carts-dep.yaml
  - 02-carts-svc.yaml
  #- carts-canary.yaml
  - carts-hpa.yaml
images:
  - name: carts
    newName: carts
    newTag: 1.0.0