---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  labels:
    app: front-end
    version: v1
  namespace: sock-shop
spec:
  progressDeadlineSeconds: 180
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      name: front-end
      app: front-end
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        name: front-end
        app: front-end
        version: v1
    spec:
      containers:
        - name: front-end
          image: europe-west3-docker.pkg.dev/cnpe-blue/sockshop/front-end:1.0.2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2000m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 300Mi
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: SESSION_REDIS
              value: "true"
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 9898
#            initialDelaySeconds: 300
#            periodSeconds: 3
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 9898
#            initialDelaySeconds: 60
#            periodSeconds: 3
      nodeSelector:
        beta.kubernetes.io/os: linux
