apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: front-end
  namespace: sock-shop
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-end
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 600
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    name: front-end
  service:
    name: front-end
    port: 80
    targetPort: 8079
    portName: http #grpc
    gateways:
      - istio-system/public-gateway
    hosts:
    - "*"
#    trafficPolicy:
#      tls:
#        # use ISTIO_MUTUAL when mTLS is enabled
#        mode: ISTIO_MUTUAL

  analysis:
    # schedule interval (default 60s)
    interval: 30s
    # max number of failed metric checks before rollback
    threshold: 25
    # precentage before complete rollout
    maxWeight: 70
    # 10% steps
    stepWeight: 10
    # promotion increment step (default 100)
    stepWeightPromotion: 100


 #   webhooks:
    #gate waits for status code 200 from an url. If it gets 403, rollout
    #will be blocked (could be used by the controller in the dashboard)
    #      - name: "gate"
    #            type: confirm-rollout
    #            url: http://flagger-loadtester.test/gate/halt

#          - name: load-test
#            url: http://34.159.190.137//
#            timeout: 5s
#            metadata:
#              type: cmd
#            cmd: ["-c", "while true; do locust --host http://34.159.190.137/ -f /config/locustfile.py --clients 5 --hatch-rate 5 --num-request 100 --no-web; done"]
    #Built in Flagger metrics
    metrics:
      - name: istio_requests_total
        thresholdRange:
          min: 99
        interval: 1m
      - name: istio_request_duration_seconds_bucket
        thresholdRange:
          max: 500
        interval: 30s
    # Istio Prometheus checks
#    metrics:
#      - name: error-rate
#        templateRef:
#          name: error-rate
#          namespace: istio-system
#        thresholdRange:
#          max: 1
#        interval: 30s
#      - name: latency
#        templateRef:
#          name: latency
#          namespace: istio-system
#        thresholdRange:
#          max: 500
#        interval: 30s

    webhooks:
#      - name: acceptance-test
#        type: pre-rollout
#        url: http://flagger-loadtester.sock-shop/
#        timeout: 30s
#        metadata:
#          type: bash
#          cmd: "curl -sd 'test' http://front-end-canary.sock-shop:9898/token | grep token"
      - name: load-test
        url: http://flagger-loadtester.sock-shop/
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://front-end.sock-shop:8079/"