---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  labels:
    name: user-db
    app: user-db
    version: v1
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-db
      app: user-db
      version: v1
  template:
    metadata:
      labels:
        name: user-db
        app: user-db
        version: v1
    spec:
      containers:
      - name: user-db
        image: europe-west3-docker.pkg.dev/cnpe-blue/sockshop/user-db:latest

        ports:
        - name: mongo
          containerPort: 27017
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 500Mi
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
