apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: frontend
  namespace: sock-shop
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: frontend
  service:
    name: frontend
    # container port
    port: 80
    # Istio gateways (optional)
    targetPort: 8079
    portName: http
    gateways:
      - public-gateway.sock-shop.svc.cluster.local
    # Istio virtual service host names (optional)
    hosts:
 #     - frontend.transparent-sock-shop.de
      - "*"

    match:
      - uri:
          prefix: /
    rewrite:
      uri: /
    trafficPolicy:
      tls:
        # use ISTIO_MUTUAL when mTLS is enabled
        mode: DISABLE

  analysis:
    # schedule interval (default 60s)
    interval: 30s
    # max number of failed metric checks before rollback
    threshold: 25
    # precentage before complete rollout
    maxWeight: 70
    # 10% steps
    stepWeight: 10
    # promotion increment step (default 100)
    stepWeightPromotion: 100
    # canary match condition
#    match:
#      - headers:
#          user-agent:
#            regex: ".*Firefox.*"
#            #regex: "^(?!.*(?:Chrome|Edge)).*Safari"
#      - headers:
#          cookie:
#            regex: "^(.*?;)?(type=insider)(;.*)?$"
    # Istio Prometheus checks
#    metrics:
#      - name: request-success-rate
#        interval: 1m
#        # minimum req success rate (non 5xx responses)
#        # percentage (0-100)
#        thresholdRange:
#          min: 99
#      - name: request-duration
#        interval: 1m
#        # maximum req duration P99
#        # milliseconds
#        thresholdRange:
#          max: 500
#      - name: error-rate
#        templateRef:
#          name: error-rate
#          namespace: istio-system
#        thresholdRange:
#          max: 1
#        interval: 30s
#      - name: latency
#        templateRef:
#          name: latency
#          namespace: istio-system
#        thresholdRange:
#          max: 500
#        interval: 30s
    # tests
#    webhooks:
#      - name: conformance-test
#        type: pre-rollout
#        timeout: 15s
#        url: http://flagger-loadtester.sock-shop/
#        metadata:
#          type: bash
#          cmd: "curl -sd 'test' http://frontend-canary.sock-shop:9898/token | grep token"
      - name: load-test
        type: rollout
        timeout: 15s
        url: http://flagger-loadtester.sock-shop/
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 -H 'Cookie: type=insider' http://frontend.sock-shop:8079/"