apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- canary.yaml
- deployment.yaml
- hpa.yaml
images:
- name: europe-west3-docker.pkg.dev/cnpe-blue/sockshop/front-end
  newName: europe-west3-docker.pkg.dev/cnpe-blue/sockshop/front-end
  newTag: europe-west3-docker.pkg.dev/cnpe-blue/sockshop/front-end:1.0.4 # {"$imagepolicy": "flux-system:frontend"}
