apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hawk-system
  namespace: hawk-ns
spec:
  timeout: 1h
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./hawk-core
  prune: true
  validation: client