apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-operator
  namespace: flux-system
spec:
  interval: 30m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./istio/operator
  prune: true
  targetNamespace: istio-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-operator
  interval: 30m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./istio/system
  prune: true
  targetNamespace: istio-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-system
  interval: 30m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./istio/gateway
  prune: true
  targetNamespace: istio-system