apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: notification-alert
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
  - kind: Kustomization
    name: '*'
  - kind: GitRepository
    name: '*'
  - kind: imagerepository
    name: "*"
  - kind: imagepolicy
    name: "*"
  - kind: receiver
    name: "*"
  - kind: provider
    name: "*"
  - kind: alert
    name: "*"
  providerRef:
    name: notification-provider