apiVersion: v1
imagePullSecrets:
  - name: gcr-key-new-new
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","imagePullSecrets":[{"name":"gcr-key-new"}],"kind":"ServiceAccount","metadata":{"annotations":{},"creationTimestamp":"2022-02-08T01:10:56Z","name":"registry-account","namespace":"flux-system","resourceVersion":"60644544","uid":"c372ba48-ddb7-4882-8aa0-d4a96ea1ecb0"},"secrets":[{"name":"default-token-zh8pt"},{"name":"registry-account-token-x6vv6"}]}
  creationTimestamp: "2022-02-08T01:10:56Z"
  name: registry-account
  namespace: flux-system
  resourceVersion: "60647108"
  uid: c372ba48-ddb7-4882-8aa0-d4a96ea1ecb0
secrets:
  - name: default-token-zh8pt
  - name: registry-account-token-x6vv6