apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubernetes-deployment
  namespace: flux-system
spec:
  interval: 30s
  dependsOn:
    - name: istio-system
  sourceRef:
    kind: GitRepository
    name: kubernetes-deployment
  path: ./apps
  prune: true
  targetNamespace: sock-shop

