apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubernetes-deployment
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: kubernetes-deployment
  path: ./manifests
  prune: true
  targetNamespace: sock-shop

