---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  gitRepository:
    name: flux-bot
    nameSpace: flux-system
  update:
    imagePolicy:
      name: frontend
      namespace: flux-system
  commit:
    author:
      email: fluxcdbot@users.noreply.github.com
      name: fluxcdbot
    messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
  push:
    branch: master
  interval: 1m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-bot
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-bot
  namespace: flux-system
spec:
  interval: 30s
  url: git@github.com:TUB-CNPE-TB/kubernetes-deployment.git
  secretRef:
    name: kubernetes-deployment-token
  ref:
    branch: master

