apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: public-gateway
  namespace: sock-shop
spec:
  secretName: istio-ingressgateway-certs
  issuerRef:
    name: letsencrypt-prod
  commonName: "*.transparent-sock-shop.de"
  acme:
    config:
      - dns01:
          provider: cloud-dns
        domains:
          - "*.transparent-sock-shop.de"
          - "transparent-sock-shop.de"