apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: catalogue
  namespace: sock-shop
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 600
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    name: catalogue
  service:
    # container port
    port: 8080
    gateways:
      - istio-system/public-gateway
  analysis:
    # schedule interval (default 60s)
    interval: 40s
    # max number of failed metric checks before rollback
    threshold: 10
    # precentage before complete rollout
    maxWeight: 80
    # 10% steps
    stepWeight: 10
    # promotion increment step (default 100)
    stepWeightPromotion: 100
     Built in Flagger metrics
    metrics:
      - name: request-success-rate
        templateRef:
          name: request-success-rate
          namespace: istio-system
        interval: 1m
        thresholdRange:
          min: 99
      - name: request-duration
        templateRef:
          name: request-duration
          namespace: istio-system
        interval: 1m
        thresholdRange:
          max: 1000
  skipAnalysis: false
