apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 05-catalogue-dep.yaml
  - catalogue-canary.yaml
  - catalogue-hpa.yaml
images:
  - name: catalogue
    newName: catalogue
    newTag: 1.0.0