apiVersion: v1
data:
    password: ENC[AES256_GCM,data:TaQAIP3YLfOd4Asld15pxg==,iv:HKxxv9SS3YLz/Da/9tXCYuCWs4p55FDx5yhaCnhiAKw=,tag:OEhgVPQN7st/gSLX2o1IBQ==,type:str]
    user: ENC[AES256_GCM,data:pxLHMThD+fw=,iv:EFA2gozNARieLx1ZCCO8hUnurJV3fMQgT3Eg6S1ZIV8=,tag:sbiMtHnQCb6KeXHoeF30zQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: basic-auth
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-09T12:16:26Z"
    mac: ENC[AES256_GCM,data:RhZUUmc8NmDSLqkI/0+0E1+AVlVhg0lUaknaCeNaJYQdrlPvOLextEHqMYCSy1JEMF0x8wDT98fdnMztvmQCZJbwR9T+1Uav0wTy3dZeVm4ddNvs3QXmBeSVf0epeUnysrSWaw60jISF/JrE34DSqIRrG/9LnTsB6tiiY6M7SG0=,iv:ySpakiJb6cQ/Z67vDquzQDbNpbwzVjQZXQ2pd+f4lA4=,tag:0xDz1HRAjYOLmd98I7UCMA==,type:str]
    pgp:
        - created_at: "2022-02-09T12:16:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+ZPOWhAz79/AQ/+OeB9ffiKWzbq71kl6zNaBkBcDs1IepZhaafpYnvg8Nmb
            RJZiH8bUcD41WgQLqtdu5cdE2JxCXpK8A+diU9+FJD7NNALnrvhXb+JngS8qC7xr
            yaTAgExyZisaqsTEDJq7yw2+1kfmmlCfkHC977TpSbk9NaTkfJiKxevJQea5c5Oi
            1+p+7tAoTrF34fJr1b2KJGkjcZ/C1ksOHGer5FlLJXgc8vS6ZmAtiD2jvl5Scf43
            Q/007LVir8rr8EoYIllnyMZWOLiqiTKHLQtfOaN+y5NKVP6hewwwazIUmQQQb2L2
            nPJKG9ttqvKPS02EXj6CvRPz/H5gHv1nLU8UOloJQSlP0RvSAoysRdCr0pl0dlG9
            edlTgtgxpbH8JEw3mdcX+3658qeINf+pye/u0cWQFF2yeOp9CfpMut/nqwvY2O4w
            kZyWsAQbqKy1tky6wxv54K6T68pWLmPa0hSYgpZKDMQN9F/P9DZa2LLegbaJ0NoH
            CUV6b0NjUwqJI89lGv83t11lXXXIu3NyuGx1tpguJvBXXAhz908Gv+QDXVYs2H6v
            UcW25/HtdpLoaTzxUD5hR1usmpzkJQUD7LCdWpXZ+u2oTb1SHtrMOEaKyGkvMx3M
            vDy0leBlbmokLhJw9CMpn4t7nyJVqLZn9lN+9Hi6DSzOQfXDldlt3XcZXlEW+o/U
            aAEJAhCmn5HsV/Wh4KTCHlTssjMceRHWdhk9NGz0u5XzGvGmjGmlwxxMBn9Qmmrw
            0BYQut4cRpxEk4SYKPPJgnVbsHT4EAmOF21lMOun23Iz3j1/wS+Qx6S7Oye4h9Oo
            LlWs0OQKenUR
            =PFuk
            -----END PGP MESSAGE-----
          fp: 30486FCD8035392D9A47D1D66C57CA11870C2640
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
