apiVersion: v1
kind: Secret
metadata:
    name: discord-flagger-webhook
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:zJ0kMQhoeyrLVko4XIFCM5QNW0CcZawVMXokpyL4miDELI9sbWqFOciOXbvNa3X9/F2koWks5dh/bovabPqaTnGG8oY46RScMIkzWv8rH2uPCKAikOCa1uTBkZ//eo9Rrp20VNw3tUOESyTem/pCYvVA9suIMvdY,iv:gawZ6qnD2cf9THh905vlVnpze/xHuHhbxalVkR93bew=,tag:0tIzsJhD66BDVePD0Obivg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-14T08:37:27Z"
    mac: ENC[AES256_GCM,data:glUjH1w09vSegDmKi6Sf9p9oRAipq6a5kr0K5p1x4E/Y8lEK4EEFCAk+lqe1sWDtkMhEM+vaJ3kbLs+1stjm0lsTTdG2F7D14tSOuMxk20NFPmycyxfoLxQ9Ad0O04Of2wVGK99ZgQSnHLis3Pe312h/Po4hviHFbG5SlhBMkzE=,iv:xpjJlyQS1r/vYM+e07tx58hfdumKR1l+4h3hf3UhJmU=,tag:a7nXk+OESG6PD+dcK+konQ==,type:str]
    pgp:
        - created_at: "2022-02-14T08:37:27Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+ZPOWhAz79/ARAAriAxyRhltzDytOrZrjtKR+SbkF85mfZfJNO0lA4HJcQv
            /Qk2jZJSHsRlhtqQZB/BCSlA/TeRwQtFzM3COYajhnIZmET5huIA520RrnwFXbph
            rat41s+jQlIOSk/9CONdpIGu9X0ixaf8+YNhODRlWIjDwEPE+JAQgLTr2WIgOkJI
            fbpve9j398qvhDp+GurzfKDtddIVkRbK4KCHSBdeR0OkqP7mIbGXdRDYWRIILBXN
            aJMJV8FxhP3MSxZ/lGCqG8nPdGy+2PnVfJAgWGFOCkhQIp6MjUHIUrv89rjR8Q0J
            9hOCdMqNVmcnRdieUb/kQY+RFF7XYAccxZROSy/F/cg3woc7Zpv9KxBMbnlK5YMn
            skUFqRe4zNRGgcK/PYl1QPLFmdB7xRWynQya3GvXXiXVZJEIk6Y7toM2J1VXy/Ls
            5BpPc3TPbS0QTdjhxc8D48YXYbMSqpOkkhQ9bw7G1Uwk5qDG8tvg/8klAExU8VV6
            0T7sWXwml51AsOkS6jV6YonpqGANi3V7aHlTn03y8IQvFssLEPnwYFBm5t5mehwY
            XcMgzkNKQdXF8YF5AtOOCPW1+qr3DQbaO49V/VbqQtgyB6JwM68V5uBS/T68ZrnZ
            Dm4gRGqjZB0ptMa4J3U5c30IHy6tpGp2oZ6km7BDPPGHjzwGu1dp+gZwI5gvw/3U
            ZgEJAhCiBAa3qT5lMsWg1gddNWfXzMC+Lix6L8K0GLAU/uA5LbHhauSPbwzf3U6b
            HRmoeyBO0PAOumfxlFKh0NoC2VCBQnKdiyhe8Om+HVeII/V4gD2e97v/+Z+mS9Cb
            fjgenv3VZQ==
            =s2Qg
            -----END PGP MESSAGE-----
          fp: 30486FCD8035392D9A47D1D66C57CA11870C2640
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
